id: I03D92748
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:26:43+00:00'
last_modified: '2022-06-08T12:02:53.935464+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27481
  title: གསུང་འབུམ། འཇམ་དབྱངས་དཔལ་ལྡན་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    06F8:
      image_group_id: I4351
      title: ''
      total_pages: 510
      order: 1
      base_file: 06F8.txt
    '4347':
      image_group_id: I4352
      title: ''
      total_pages: 500
      order: 2
      base_file: 4347.txt
    6F3D:
      image_group_id: I4353
      title: ''
      total_pages: 598
      order: 3
      base_file: 6F3D.txt
    '7044':
      image_group_id: I4354
      title: ''
      total_pages: 522
      order: 4
      base_file: 7044.txt
    3E37:
      image_group_id: I4355
      title: ''
      total_pages: 522
      order: 5
      base_file: 3E37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
