id: P007017
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:29.057836
source_metadata:
  id: bdr:W27481
  title: གསུང་འབུམ། འཇམ་དབྱངས་དཔལ་ལྡན་རྒྱ་མཚོ
  author: ''
  volumes:
    54c33e6121b14821879f062db006c8e7:
      image_group_id: I4351
      title: ''
      volume_number: 1
      total_pages: 510
      base_file: v001.txt
    589384b0ab164044bbee48e208cba180:
      image_group_id: I4352
      title: ''
      volume_number: 2
      total_pages: 500
      base_file: v002.txt
    779cb000b70a44a09dadff6043908cee:
      image_group_id: I4353
      title: ''
      volume_number: 3
      total_pages: 598
      base_file: v003.txt
    e06cf9899c284ffe8798f3659474ce15:
      image_group_id: I4354
      title: ''
      volume_number: 4
      total_pages: 522
      base_file: v004.txt
    3ab5c7c09a07405ab06a1de634ba4c90:
      image_group_id: I4355
      title: ''
      volume_number: 5
      total_pages: 522
      base_file: v005.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
